#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "用法：$0 <镜像标签>" >&2
  exit 1
fi

IMAGE_TAG="$1"
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
META_FILE="$ROOT_DIR/release-meta.env"
INCOMING_GHCR_USERNAME="${GHCR_USERNAME:-}"
INCOMING_GHCR_TOKEN="${GHCR_TOKEN:-}"

if [[ ! -f "$META_FILE" ]]; then
  echo "[部署] 缺少配置文件：$META_FILE" >&2
  echo "[部署] 请在 ECS 上复制 release-meta.env.example 为 release-meta.env，并填入真实密钥。" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$META_FILE"
set +a

GHCR_USERNAME="${GHCR_USERNAME:-$INCOMING_GHCR_USERNAME}"
GHCR_TOKEN="${GHCR_TOKEN:-$INCOMING_GHCR_TOKEN}"

: "${GHCR_BASE:?请在 release-meta.env 设置 GHCR_BASE}"
: "${COMPOSE_FILE:?请在 release-meta.env 设置 COMPOSE_FILE}"
: "${RUNTIME_ENV_FILE:?请在 release-meta.env 设置 RUNTIME_ENV_FILE}"
: "${METADATA_DIR:?请在 release-meta.env 设置 METADATA_DIR}"
: "${API_TOKEN:?请在 release-meta.env 设置 API_TOKEN}"
: "${VNC_PASSWORD:?请在 release-meta.env 设置 VNC_PASSWORD}"

APP_ENV="${APP_ENV:-prod}"
HOST_API_BIND="${HOST_API_BIND:-127.0.0.1}"
HOST_API_PORT="${HOST_API_PORT:-18000}"
HOST_NOVNC_BIND="${HOST_NOVNC_BIND:-127.0.0.1}"
HOST_NOVNC_PORT="${HOST_NOVNC_PORT:-6080}"
HOST_BROWSER_DATA_DIR="${HOST_BROWSER_DATA_DIR:-/root/browser-ai-relay-data/browser_data}"
HOST_LOGS_DIR="${HOST_LOGS_DIR:-/root/browser-ai-relay-data/logs}"
BROWSER_MODE="${BROWSER_MODE:-ecs_cdp}"
CDP_URL="${CDP_URL:-http://127.0.0.1:9222}"
CDP_CONNECT_TIMEOUT_SECONDS="${CDP_CONNECT_TIMEOUT_SECONDS:-60}"
ATTACH_ON_START="${ATTACH_ON_START:-false}"
CHATGPT_URL="${CHATGPT_URL:-https://chatgpt.com/}"
CHAT_TIMEOUT_SECONDS="${CHAT_TIMEOUT_SECONDS:-120}"
RESPONSE_STABLE_SECONDS="${RESPONSE_STABLE_SECONDS:-5}"
ENABLE_STEALTH="${ENABLE_STEALTH:-true}"
SLOW_MO_MS="${SLOW_MO_MS:-50}"
VIEWPORT_WIDTH="${VIEWPORT_WIDTH:-1366}"
VIEWPORT_HEIGHT="${VIEWPORT_HEIGHT:-768}"
VIEWPORT_JITTER_PX="${VIEWPORT_JITTER_PX:-20}"
BROWSER_CHANNEL="${BROWSER_CHANNEL:-chrome}"
BEFORE_TYPE_DELAY_MIN_MS="${BEFORE_TYPE_DELAY_MIN_MS:-500}"
BEFORE_TYPE_DELAY_MAX_MS="${BEFORE_TYPE_DELAY_MAX_MS:-1200}"
BEFORE_SEND_DELAY_MIN_MS="${BEFORE_SEND_DELAY_MIN_MS:-300}"
BEFORE_SEND_DELAY_MAX_MS="${BEFORE_SEND_DELAY_MAX_MS:-600}"
TYPING_DELAY_MIN_MS="${TYPING_DELAY_MIN_MS:-0}"
TYPING_DELAY_MAX_MS="${TYPING_DELAY_MAX_MS:-0}"
LOG_LEVEL="${LOG_LEVEL:-INFO}"

LOG_DIR="${DEPLOY_LOG_DIR:-$ROOT_DIR/logs}"
mkdir -p "$LOG_DIR" "$METADATA_DIR" "$HOST_BROWSER_DATA_DIR" "$HOST_LOGS_DIR"
LOG_FILE="$LOG_DIR/deploy-$(date +%Y%m%d).log"
exec > >(tee -a "$LOG_FILE") 2>&1

CURRENT_ENV="$METADATA_DIR/current.env"
PREVIOUS_ENV="$METADATA_DIR/previous.env"

if [[ -f "$CURRENT_ENV" ]]; then
  cp "$CURRENT_ENV" "$PREVIOUS_ENV"
fi

cat > "$CURRENT_ENV" <<ENV
BROWSER_AI_RELAY_IMAGE=${GHCR_BASE}/browser-ai-relay:${IMAGE_TAG}

APP_ENV=${APP_ENV}
API_TOKEN=${API_TOKEN}
VNC_PASSWORD=${VNC_PASSWORD}

HOST_API_BIND=${HOST_API_BIND}
HOST_API_PORT=${HOST_API_PORT}
HOST_NOVNC_BIND=${HOST_NOVNC_BIND}
HOST_NOVNC_PORT=${HOST_NOVNC_PORT}
HOST_BROWSER_DATA_DIR=${HOST_BROWSER_DATA_DIR}
HOST_LOGS_DIR=${HOST_LOGS_DIR}

BROWSER_MODE=${BROWSER_MODE}
CDP_URL=${CDP_URL}
CDP_CONNECT_TIMEOUT_SECONDS=${CDP_CONNECT_TIMEOUT_SECONDS}
ATTACH_ON_START=${ATTACH_ON_START}

CHATGPT_URL=${CHATGPT_URL}
CHAT_TIMEOUT_SECONDS=${CHAT_TIMEOUT_SECONDS}
RESPONSE_STABLE_SECONDS=${RESPONSE_STABLE_SECONDS}

ENABLE_STEALTH=${ENABLE_STEALTH}
SLOW_MO_MS=${SLOW_MO_MS}
VIEWPORT_WIDTH=${VIEWPORT_WIDTH}
VIEWPORT_HEIGHT=${VIEWPORT_HEIGHT}
VIEWPORT_JITTER_PX=${VIEWPORT_JITTER_PX}
BROWSER_CHANNEL=${BROWSER_CHANNEL}
BEFORE_TYPE_DELAY_MIN_MS=${BEFORE_TYPE_DELAY_MIN_MS}
BEFORE_TYPE_DELAY_MAX_MS=${BEFORE_TYPE_DELAY_MAX_MS}
BEFORE_SEND_DELAY_MIN_MS=${BEFORE_SEND_DELAY_MIN_MS}
BEFORE_SEND_DELAY_MAX_MS=${BEFORE_SEND_DELAY_MAX_MS}
TYPING_DELAY_MIN_MS=${TYPING_DELAY_MIN_MS}
TYPING_DELAY_MAX_MS=${TYPING_DELAY_MAX_MS}
LOG_LEVEL=${LOG_LEVEL}
ENV

cp "$CURRENT_ENV" "$RUNTIME_ENV_FILE"
chmod 600 "$RUNTIME_ENV_FILE"

if [[ -n "${GHCR_USERNAME:-}" && -n "${GHCR_TOKEN:-}" ]]; then
  echo "[部署] 登录 GHCR"
  echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
fi

compose=(docker compose --env-file "$RUNTIME_ENV_FILE" -f "$COMPOSE_FILE")

echo "[部署] 拉取镜像 ${GHCR_BASE}/browser-ai-relay:${IMAGE_TAG}"
"${compose[@]}" pull

echo "[部署] 启动 browser-ai-relay"
"${compose[@]}" up -d

if "$ROOT_DIR/healthcheck.sh"; then
  echo "[部署] 成功"
  exit 0
fi

echo "[部署] 健康检查失败，尝试回滚"
"$ROOT_DIR/rollback.sh"
exit 1
